import { readFileSync } from "node:fs";

export default function (eleventyConfig) {
  // CMS-edited content (re-read every build so --serve picks up changes)
  eleventyConfig.addGlobalData("site", () =>
    JSON.parse(readFileSync("content/site.json", "utf8"))
  );

  // Everything ships as-is except: the four HTML pages (processed as Nunjucks
  // for the few templated values) and js/i18n.js (generated by i18n.11ty.js).
  eleventyConfig.addPassthroughCopy("css");
  eleventyConfig.addPassthroughCopy("assets");
  eleventyConfig.addPassthroughCopy("js/site.js");
  eleventyConfig.addWatchTarget("content/");

  // repo image paths need a leading slash; absolute URLs pass through
  eleventyConfig.addFilter("imgsrc", (v) => (/^https?:/.test(v) ? v : "/" + v));

  eleventyConfig.ignores.add("README.md");
  eleventyConfig.ignores.add("docs/**");

  // Keep original URLs (about.html, not /about/) so existing links don't break.
  eleventyConfig.addGlobalData("permalink", () => (data) => `${data.page.filePathStem}.html`);

  return {
    dir: { input: ".", output: "_site" },
    htmlTemplateEngine: "njk",
  };
}
