import { readFileSync } from "node:fs";
import { buildDict } from "./lib/i18n-dict.mjs";
import { loadRetreats } from "./lib/retreats.mjs";
import { loadReviews } from "./lib/reviews.mjs";

const escapeText = (s) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const escapeAttr = (s) => escapeText(s).replace(/"/g, "&quot;");

export default function (eleventyConfig) {
  // CMS-edited content (re-read every build so --serve picks up changes)
  eleventyConfig.addGlobalData("site", () =>
    JSON.parse(readFileSync("content/site.json", "utf8"))
  );

  // Everything ships as-is except: the four HTML pages (processed as Nunjucks
  // for the few templated values) and js/i18n.js (generated by i18n.11ty.js).
  eleventyConfig.addPassthroughCopy("css");
  eleventyConfig.addPassthroughCopy("assets");
  eleventyConfig.addPassthroughCopy("js/site.js");
  eleventyConfig.addPassthroughCopy("js/moments-wall.js");
  eleventyConfig.addPassthroughCopy("js/values-constellation.js");
  eleventyConfig.addPassthroughCopy("js/reviews-carousel.js");
  eleventyConfig.addWatchTarget("content/");

  // keep repo image paths relative (no leading slash) so the site works at a
  // GitHub Pages sub-path (/Munay2/) as well as a root domain; absolute URLs pass through
  eleventyConfig.addFilter("imgsrc", (v) => (/^https?:/.test(v) ? v : v.replace(/^\/+/, "")));

  eleventyConfig.ignores.add("README.md");
  eleventyConfig.ignores.add("docs/**");

  // Upcoming retreats, read from the client's Google Sheet at build time.
  // Unset RETREATS_SHEET_URL renders the evergreen empty state; a damaged
  // sheet throws, which fails the build and leaves the last deploy live.
  eleventyConfig.addGlobalData("retreats", () => loadRetreats());

  // Client reviews, read from a second tab of the same sheet. Unset
  // REVIEWS_SHEET_URL renders the evergreen fallback quote on the home page;
  // a damaged sheet throws, which fails the build and leaves the last deploy
  // live. Review text is never translated, so nothing here touches the i18n
  // dictionary the way retreat dates do.
  eleventyConfig.addGlobalData("reviews", () => loadReviews());

  // Prerender the default-language (English) copy into the HTML at build time so
  // crawlers / no-JS visitors see real content. The client-side js/i18n.js still
  // runs on top: it overwrites textContent on load (no-op for English, swaps for
  // ES/FA). data-i18n elements are verified text-only leaves, so a scoped regex
  // is safe; see lib/i18n-dict.mjs for the (shared) dictionary source.
  eleventyConfig.addTransform("i18n-prerender", async function (content) {
    if (!(this.page.outputPath || "").endsWith(".html")) return content;
    const en = (await buildDict()).en;

    // Fill textContent of <tag ... data-i18n="key">…</tag>
    let out = content.replace(
      /(<([a-zA-Z0-9]+)\b[^>]*\bdata-i18n="([^"]+)"[^>]*>)([\s\S]*?)(<\/\2>)/g,
      (m, open, _tag, key, _inner, close) =>
        en[key] == null ? m : open + escapeText(en[key]) + close
    );

    // Set placeholder="…" on <tag ... data-i18n-ph="key" …> (often self-closing)
    out = out.replace(
      /<([a-zA-Z0-9]+)\b([^>]*\bdata-i18n-ph="([^"]+)"[^>]*?)(\s*\/?)>/g,
      (m, tag, attrs, key, tail) => {
        if (en[key] == null) return m;
        const ph = `placeholder="${escapeAttr(en[key])}"`;
        const next = /\bplaceholder="[^"]*"/.test(attrs)
          ? attrs.replace(/\bplaceholder="[^"]*"/, ph)
          : `${attrs} ${ph}`;
        return `<${tag}${next}${tail}>`;
      }
    );

    return out;
  });

  // Keep original URLs (about.html, not /about/) so existing links don't break.
  eleventyConfig.addGlobalData("permalink", () => (data) => `${data.page.filePathStem}.html`);

  return {
    dir: { input: ".", output: "_site" },
    htmlTemplateEngine: "njk",
  };
}
